[package]
name = "des"
version = "0.1.0"
description = "An implementation of the Data Encryption Standard (DES) cipher"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
edition = "2021"

[dependencies]
