[package]
name = "aes"
version = "0.1.0"
description = "An implementation of the Advanced Encryption Standard (AES) cipher"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
edition = "2021"

[dependencies]
