[package]
name = "polybius-square"
version = "0.1.0"
description = "An implementation of Polybius Square cipher"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
edition = "2021"

[dependencies]
